version: '3'

services:
  backend:
    
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./my-app
      dockerfile: ./Dockerfile
    image: "frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"